mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
#    path("__debug__/", include("debug_toolbar.urls")),
    # path("", include("polls.urls")),
    path('admin/', admin.site.urls),
    path("shop/", include("shop.urls")),
    path("", include("shop.urls")),
    path("<category>", include("shop.urls")),
    # path("<int:category_id>", include("shop.urls")),
    # path("polls/", include("polls.urls")),
]

from django.conf import settings
if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

shop/urls.py
from django.urls import path

from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.show_products, name='index'),
    path('static/shop/images/<str:name>', views.images, name='images'),
    path('add-basket/<int:id>', views.add_basket, name='add-basket'),
    path('show-basket/', views.show_basket, name='show-basket'),
    path('delete-basket/', views.delete_basket, name='delete-basket'),
    path('delete-item-basket/<int:id>', views.delete_item_basket,
            name='delete-item-basket'),
    path('reservation/', views.reservation_form, name='reservation'),
    path('summary/', views.post_reservation_form, name='summary'),
    path('invoice/<int:id>', views.get_invoice, name='invoice'),
    path('<category>', views.show_products, name='show-products'),
]

shop/models.py
from django.db import models
from django.contrib.humanize.templatetags.humanize import naturaltime
from django.utils.translation import gettext_lazy as _

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=255, verbose_name=_('Name'))
    description = models.CharField(max_length=255,
                                   verbose_name=_('Description'))

    def __str__(self):
        return f'{self.name.capitalize()}'

    class Meta:
        verbose_name = _('Category')
        verbose_name_plural = _('Categories')

class Product(models.Model):
    name = models.CharField(max_length=255, verbose_name=_('Name'),
                            unique=True)
    description = models.CharField(max_length=255,
                                   verbose_name=_('Description'))
    price = models.DecimalField(max_digits=12, decimal_places=2, default=0,
                                verbose_name=_('Price'))
    image = models.ImageField(upload_to='shop\static\shop\images',
                              verbose_name=_('Image'))
    category = models.ForeignKey(Category, null=True, blank=True,
            on_delete=models.CASCADE, verbose_name=_('Category'),
            related_name=_('Products'))
    
    def __str__(self):
        return f'{self.name} {self.description} {self.price}'

    class Meta:
        verbose_name = _('Product')
        verbose_name_plural = _('Products')
        indexes = [models.Index(fields=['name']), ]



class Reservation(models.Model):
    date = models.DateTimeField(verbose_name=_('Date'))
    first_name = models.CharField(max_length=255, verbose_name=_('First name'))
    last_name = models.CharField(max_length=255, verbose_name=_('Last name'))
    phone_number = models.CharField(max_length=255,
                                    verbose_name=_('Phone number'))
    products = models.ManyToManyField(Product, through='ReservationRow',
                                      verbose_name=_('Products'))

    def __str__(self):
        return (f'[{naturaltime(self.date)}] {self.first_name} '
                f'{self.last_name.upper()} '
                f'({len(self.products.all())})')

    class Meta:
        verbose_name = _('Reservation')
        verbose_name_plural = _('Reservations')


class ReservationRow(models.Model):
    quantity = models.IntegerField(verbose_name=_('Quantity'))
    reduction = models.DecimalField(max_digits=12, decimal_places=2, default=0,
                                    verbose_name=_('Reduction'))
    product = models.ForeignKey(Product, on_delete=models.CASCADE,
                                verbose_name=_('Product'))
    reservation = models.ForeignKey(Reservation, on_delete=models.CASCADE,
                                    verbose_name=_('Reservation'))

    def __str__(self):
        return f'quantity: {self.quantity} reduction: {self.reduction}'

    class Meta:
        verbose_name = _('Reservation row')
        verbose_name_plural = _('Reservation rows')

shop/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _


class ResevationForm(forms.Form):
    datetime = forms.DateTimeField(label=_('Day and time'))
    first_name = forms.CharField(label=_('First name'), max_length=255)
    last_name = forms.CharField(label=_('Last name'), max_length=255)
    phone_number = forms.CharField(label=_('Phone number'), max_length=255)

    datetime.widget.attrs.update({'class': 'input'})
    datetime.widget.input_type = 'datetime-local'
    first_name.widget.attrs.update({'class': 'input'})
    last_name.widget.attrs.update({'class': 'input'})
    phone_number.widget.attrs.update({'class': 'input',
                                      'pattern': '^\+?[\s\d]{1,30}'})

shop/views.py
from django.shortcuts import render, redirect
from .models import Product, ReservationRow, Reservation, Category
from django.http import HttpResponse
from functools import reduce, singledispatch
from .forms import ResevationForm
import sys

def set_url_image(product):
    try:
        product['image'] =  product['image'][11:] 
    except TypeError as e:
        print(type(e), e, file=sys.stderr)
        product.image =  product.image.name[11:] 
    return product


def show_products(request, category=None):
    try:
        products= get_products(int(category))
    except Exception as _:
        products = get_products(category)
    context = dict()
    context['categories'] = Category.objects.all().values('name')
    context['products'] = list(map(set_url_image, products))
    context['basketQuantity'] = get_basket(request)
    context['category_now'] = category
    return render(request, 'shop/index.html', context)

@singledispatch
def get_products(category: None):
    return Product.objects.all().values()

@get_products.register
def _(category: str):
    return Product.objects.filter(category__name=category).values()

@get_products.register
def _(category: int):
    return Product.objects.filter(category__id=category).values()


def get_basket(request):
    try:
        basket = request.session['basket']
        return len(basket)
    except KeyError as e:
        print(type(e), e, file=sys.stderr)
    return 0

def images(request, name):
    context = dict()
    context['src'] = 'shop/images/' + name
    return render(request, 'shop/images.html', context)

def add_basket(request, id):
    try:
        return_text = ''
        basket = request.session['basket']
        return_text += str(request.session['basket'])
        basket.append(id)
        return_text += str(request.session['basket'])
        request.session['basket'] = basket
        return redirect('shop:index')
    except (KeyError, AttributeError) as e:
        print(type(e), e, file=sys.stderr)
        request.session['basket'] = list()
        return add_basket(request, id)


def get_data_for_show_basket(id):
    try:
        return Product.objects.get(id=id)
    except Exception as e:
        print(type(e), e, file=sys.stderr)

def get_basket_with_url(basket):
    basket_data = tuple(map(get_data_for_show_basket, basket))
    basket_data_noneless = tuple(filter(lambda product: product is not None,
                                       basket_data))
    basket_with_url = tuple(map(set_url_image, basket_data_noneless))
    return basket_with_url

def get_total_price(basket):
    def sum_price(accumulator, product):
        return accumulator + product.price
    total_price = reduce(sum_price, basket, 0)
    return total_price

def get_basket_from_session(request):
    try:
        basket = request.session['basket']
    except (KeyError, AttributeError) as e:
        print(type(e), e, file=sys.stderr)
        request.session['basket'] = list()
        basket = request.session['basket']
    return basket

def show_basket(request):
    basket = get_basket_from_session(request)
    basket_with_url = get_basket_with_url(basket)
    context = dict()
    context['basket'] = basket_with_url
    context['total_price'] = get_total_price(basket_with_url)
    return render(request, 'shop/basket.html', context)
    
def delete_basket(request):
    request.session['basket'] = list()
    return redirect('shop:show-basket')

def delete_item_basket(request, id):
    try:
        basket = request.session['basket']
        basket.remove(id)
        request.session['basket'] = basket
    except ValueError as e:
        print(type(e), e, file=sys.stderr)
    return redirect('shop:show-basket')

def reservation_form(request):
    context = dict()
    context['form'] = ResevationForm();
    return render(request, 'shop/reservation-form.html', context)

def post_reservation_form(request):
    try:
        context = dict()
        reservation = Reservation.objects.create(date=request.POST['datetime'],
                           first_name=request.POST['first_name'],
                           last_name=request.POST['last_name'],
                           phone_number=request.POST['phone_number'])
        basket = request.session['basket']
        formated_basket = get_quantity_each_item(basket)
        for row in formated_basket:
            product = Product.objects.get(id=row['id'])
            ReservationRow.objects.create(quantity=row['quantity'], reduction=0,
                                  product=product, reservation=reservation)
        request.session['basket'] = list()
        return render(request, 'shop/summary.html', context)
    except Exception as e:
        print(type(e), e, file=sys.stderr)

    

def get_quantity_each_item(basket: list[int]):
    def get_quantity_and_id(item: int):
        row = dict()
        row['quantity'] =basket.count(item)
        row['id'] = item
        return row
    count_basket = tuple(map(get_quantity_and_id, basket))
    def remove_duplicate(acc, item):
        if item not in acc:
            acc.append(item)
        return acc
    duplicateless_count_basket = reduce(remove_duplicate, count_basket, list())
    return duplicateless_count_basket


def get_invoice(request, id):
    context = dict()
    reservation = Reservation.objects.get(id=id)
    reservation_rows = reservation.reservationrow_set.all()
    def format_reservation(row):
        data = dict()
        data['image'] = row.product.image.name[11:]
        data['name'] = row.product.name
        data['description'] = row.product.description
        data['quantity'] = row.quantity
        data['unit_price'] = row.product.price
        data['amount'] = data['quantity'] * data['unit_price']
        return data
    formated_reservation = tuple(map(format_reservation, reservation_rows))
    context['formated_reservation'] = formated_reservation
    context['reservation'] = reservation
    context['total_price'] = reduce(lambda acc, row: acc + row['amount'],
                            formated_reservation, 0)
    return render(request, 'shop/invoice.html', context)

shop/templates/shop/basket.html
{% load static %}
{% load i18n %}
{% translate 'Basket' as title%}
<!DOCTYPE html>
<html lang="fr-CH">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ title }}</title>
    <link rel="stylesheet" href="{% static 'shop/bulma.min.css' %}">
  </head>
  <body>
  <section class="section">
    <div class="container">
      <h1 class="title">
        {{ title }}
      </h1>
      <p class="subtitle">
      {% translate 'Check your basket' %}
      </p>
      <p class="block">
      <a href="{% url 'shop:index' %}" class='button is-link '>{% translate 'Return'%}</a>
      {% if basket|length == 0 %}
        <button disabled class='button is-primary '>{% translate 'Next'%}</button>
      {% else %}
        <a href="{% url 'shop:reservation' %}" class='button is-primary '>{% translate 'Next'%}</a>
      {% endif %}
      </p>
      <table class="table">
        <thead>
          <tr>
            <th>{% translate 'Image' %}</th>
            <th>{% translate 'Name' %}</th>
            <th>{% translate 'Description' %}</th>
            <th>{% translate 'Price' %}</th>
            <th></th>
          </tr>
        </thead>
        {% for product in basket %}
          <tr>
            <td><img class="image" width="128" src="{% static product.image %}"></td>
            <td>{{ product.name|capfirst }}</td>
            <td>{{ product.description }}</td>
            <td>{{ product.price }}</td>
            <td><a href="{% url 'shop:delete-item-basket'  product.id %}" class="button is-danger">{% translate 'Delete'%}</a></td>
          </tr>
        {% endfor %}
        <tfoot>
          <tr>
            <td colspan="3">{% translate 'Total price:' %}</td>
            <td colspan="2">{{ total_price }}</td>
            <tr>
        </tfoot>
      </table>
      <a href="{% url 'shop:delete-basket'%}" class="button is-danger">{% translate 'Delete all'%}</a>
    </div>
  </section>
  </body>
</html>

shop/templates/shop/category-buttons.html
{% load i18n %}
<div class="buttons">
  <a class="button {% if category_now == None %} is-active{% endif %}" href="{% url 'shop:index' %}">
      {% translate 'All' %}
  </a>
  {% for category in categories %}
    <a class="button {% if category_now == category.name %} is-active{% endif %}"
      href="{% url 'shop:show-products' category.name %}"
    >
      {{ category.name|capfirst }}
    </a>
  {% endfor %}
</div>

shop/templates/shop/images.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Image</title>
    <link rel="stylesheet" href="{% static 'shop/bulma.min.css' %}">
  </head>
  <body lang="fr-CH">
  <section class="section">
    <div class="container">
      <h1 class="title">Image</h1>
      <p class="subtitle">
          <img src="{% static src %}">
      </p>
    </div>
  </section>
  </body>
</html>

shop/templates/shop/index.html
{% load static %}
{% load i18n %}

{% translate 'Shop' as title %}
<!DOCTYPE html>
<html lang='fr-CH'>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ title }}</title>
    <script>
      let itemQuantity = {{ basketQuantity }};
    </script>
    <script src="{% static 'shop/scripts/addItem.js' %}"></script>
    <link rel="stylesheet" href="{% static 'shop/bulma.min.css' %}">
  </head>
  <body>
  <section class="section">
    <div class="container">
      <h1 class="title">
        {{ title }}
      </h1>
      <p  class="subtitle">
        {% translate 'Add products in your basket' %}
      </p>
      <p class="block">
        <a href="{% url 'shop:show-basket' %}" class='button is-link '>
          {% translate 'Check your basket'%} (<span id="basket-counter"> </span>)
        </a>
      </p>
      <p class="block">
        {% include "shop/category-buttons.html" with categories=categories %}
      </p>
      <div class="columns is-multiline">
        {% for product in products %}
          <div class="column is-one-quarter">
            {% include "shop/product.html" with product=product %}
          </div>
        {% endfor %}
      </div>
    </div>
  </section>
  </body>
</html>

shop/templates/shop/invoice.html
{% load static %}
{% load i18n %}
{% translate 'Invoice' as title%}
{% load humanize %}
<!DOCTYPE html>
<html lang="fr-CH">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ title }}</title>
    <link rel="stylesheet" href="{% static 'shop/bulma.min.css' %}">
  </head>
  <body>
    {% if user.is_authenticated %}
      <section class="section">
        <div class="container">
          <h1 class="title">
            {{ title }}
          </h1>
          <p class="subtitle">
          {% now "DATETIME_FORMAT" %}
          </p>
          <p>{% translate 'First name: ' %}{{ reservation.first_name }}</p>
          <p>{% translate 'Last name: ' %}{{ reservation.last_name }}</p>
          <p>{% translate 'Phone number: ' %}{{ reservation.phone_number }}</p>
          <p>{% translate 'For: ' %}{{reservation.date}} ({{ reservation.date|naturaltime }})</p>
          <table class="table">
            <thead>
              <tr>
                <th>{% translate 'Quantity' %}</th>
                <th>{% translate 'Image' %}</th>
                <th>{% translate 'Name' %}</th>
                {% comment %}
                <th>{% translate 'Description' %}</th>
                {% endcomment %}
                <th>{% translate 'Unit Price' %}</th>
                <th>{% translate 'Amount' %}</th>
                <th></th>
              </tr>
            </thead>
            {% for product in formated_reservation %}
              <tr>
                <td>{{ product.quantity }}</td>
                <td><img class="image" width="128" src="{% static product.image %}"></td>
                <td>{{ product.name|capfirst }}</td>
                {% comment %}
                <td>{{ product.description }}</td>
                {% endcomment %}
                <td>{{ product.unit_price }}</td>
                <td>{{ product.amount }}</td>
              </tr>
            {% endfor %}
            <tfoot>
              <tr>
                <td colspan="4">{% translate 'Total price:' %}</td>
                <td colspan="1">{{ total_price }}</td>
                <tr>
            </tfoot>
          </table>
        </div>
      </section>
    {% else %}
      <p>{% translate 'Unauthorised' %}</p>
    {% endif%}
  </body>
</html>

shop/templates/shop/product.html
{% load static %}
{% load i18n %}
<div class="card">
  <div class="card-image">
    <figure class="image">
      <img src="{% static product.image %}">
    </figure>
  </div>
  <div class="card-content">
    <h2 class="title is-2">{{ product.name|capfirst }}</h2>
    <p>{{ product.description }}</p>
    <strong>{{ product.price }}</strong>
    <div class="block">
      <button onClick="addItem(this, '{% url 'shop:add-basket' product.id %}')" class="button is-primary">{% translate 'Add' %}</button>
    </div>
  </div>
</div>

shop/templates/shop/reservation-form.html
{% load static %}
{% load i18n %}

{% translate 'Reservation' as title%}
<!DOCTYPE html>
<html lang='fr-CH'>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ title }}</title>
    <link rel="stylesheet" href="{% static 'shop/bulma.min.css' %}">
  </head>
  <body>
  <section class="section">
    <div class="container">
      <h1 class="title">
        {{ title }}
      </h1>
      <p class="subtitle">
      {% translate 'Type your contact information' %}
      </p>
      <p class="block">
      <a href="{% url 'shop:show-basket' %}" class="button is-link">{% translate 'Return'%}</a>
      </p>
      <form action="{% url 'shop:summary' %}" method="post">
        {% csrf_token %}
        {% for field in form %}
          <div class="field">
            {{ field.errors }}
            <label class="label" for="{{ field.auto_id }}">
              {{ field.label }}
            </label>
            <div class="control">
              {{ field }}
            </div>
          </div>
        {% endfor %}
        <input type="submit" class="button is-primary" value="{% translate 'Submit' %}">
      </form>
    </div>
  </section>
  </body>
</html>

shop/templates/shop/summary.html
{% load static %}
{% load i18n %}
{% translate 'Summary' as title %}
<!DOCTYPE html>
<html lang="fr-CH">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ title }}</title>
    <link rel="stylesheet" href="{% static 'shop/bulma.min.css' %}">
  </head>
  <body>
  <section class="section">
    <div class="container">
      <h1 class="title">
        {{ title }}
      </h1>
      <p class="subtitle">
      {% translate 'Your reservation has been sended.' %}
      </p>
      <p class="block">
      <a href="{% url 'shop:index' %}" class="button is-primary">{% translate 'Home' %}</a>
      </p>
    </div>
  </section>
  </body>
</html>